# This file extends docker-compose.yml
version: "3"

services:
  xswitch-pg:
    container_name: "xswitch-pg"
    image: ccr.ccs.tencentyun.com/customers/xswitch-pg:latest
    network_mode: "host"
    restart: always
    env_file: ./.env
    volumes:
      - ./postgres:/var/lib/postgresql/data