---

docker_package: "docker-ce docker-ce-cli containerd.io docker-compose-plugin"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
#docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true
docker_apt_gpg_key: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
#docker_apt_gpg_key: https://mirrors.tuna.tsinghua.edu.cn/docker-ce/linux/{{ ansible_distribution | lower }}/gpg

# A list of users who will be added to the docker group.
docker_users: []