# This file extends docker-compose.yml
version: "3"

services:
  xswitch-lua:
    container_name: "xswitch-lua"
    image: ccr.ccs.tencentyun.com/xswitch-cloud/xswitch:v4.0.2-cloud-lua
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200m"
    restart: always
    env_file: ./.env
    ulimits:
      core: -1
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - ./log:/usr/local/freeswitch/log
      - ./storage:/usr/local/freeswitch/storage
      - ./sounds:/usr/local/freeswitch/sounds
      - ./xtra_config.lua:/usr/local/freeswitch/xui/lua/xui/xtra_config.lua
    depends_on:
      - xswitch-pg

  xswitch-nginx-xui:
    container_name: "xswitch-nginx-xui"
    image: ccr.ccs.tencentyun.com/xswitch-cloud/xswitch:v4.0.2-cloud-nginx-xui
    network_mode: "host"
    restart: always
    env_file: ./.env
    volumes:
      - ./storage:/usr/local/freeswitch/storage
      - ./sounds:/usr/local/freeswitch/sounds
    depends_on:
      - xswitch-lua
