---
- hosts: all
  user: root

  tasks:

    - name: update uas version
      shell: sed '5c \ \ \ \ image:\ ccr.ccs.tencentyun.com/free/cadvisor:latest' /usr/local/monitor-agent/docker-compose.yml

    - name: update uas version2
      shell: sed '18c \ \ \ \ image:\ ccr.ccs.tencentyun.com/free/node-exporter:1.0.0' /usr/local/monitor-agent/docker-compose.yml
    - include: roles/prometheus-node-install/tasks/node_down.yml

    - include: roles/prometheus-node-install/tasks/node_up.yml
